### ISSUE TITLE
"difficult to get into"

### ISSUE THREAD

**Issue by cdent** [martynbristow/gabbi-examples#1]
Hey, this seemed like the best way to contact you about this.

I'm the author of gabbi, and was very pleased to stumble across your blog posting and then this repo. It would be great to hear more about the difficulties you had getting started so that I (or other gabbi contributors) could fix things. Feel free to respond here, create a [issue on gabbi itself](https://github.com/cdent/gabbi/issues), or find us in the #gabbi IRC channel on free node.

I suspect there's a lot of presumed background in docs and general interface to gabbi that could be improved a great deal. It's challenging to do without interacting with real people, though, so your help would be most welcome.

**Comment by martynbristow** [comment]
Hello
I'm very impressed with gabbi, it's simple and readable, which is really useful for tests in my opinion. I'm testing a PHP app and some other things. Sadly I haven't looked into much if these lately as my real job has been keeping me occupied.
I had some problems working out cookie authentication and other setups.
I'll try and finish it off 😁
I spoke about it to our Python user group last week as well

**Comment by cdent** [comment]
For cookie-based authentication what I've tended to do is acquire or construct the cookie before entering the gabbi tests, somewhat like you've done with your fixture example and then referencing the cookie with $ENVIRON['cookie'] but the differences for me would be:

* If I was using a python test runner, I'd probably not use a fixture for getting the cookie under the assumption that I want the cookie throughout all my tests, so might be easier to just set the environ in the file that has `load_tests` in it.
* If I was using gabbi-run I'd use curl or something like it to fetch the cookie and install it into an environment variable which then gets references from the YAML.

Generally the assumption that gabbi makes is that you are able to acquire a cookie or other authentication token prior to entering the tests and then use that token (if you look around [near here](https://github.com/openstack/gnocchi/blob/master/gnocchi/tests/gabbi/gabbits-live/live.yaml) there are some examples).

Unless, of course, you are specifically testing the authentication interaction.

**Comment by martynbristow** [comment]
Well I want to test the authentication, its a common scenario set, I want test authentication is requested/required, but I also want just run tests on authenticated controllers. I'm also interested running database scripts before I run a batch of tests. The App and its use-cases are all still very much WIP but I'm looking to add it to Jenkins or generally automate it with commit hooks.
The authentication in CodeIgniter is a slight variation from PHP and it can be regenerated on the fly.
I'll have a look into these, ultimately I'd like to help make sure people can discover the beauty of Gabbi.

**Comment by martynbristow** [comment]
If you'd like me to prepare some more examples and step through I can prepare them you can link them in. I don't think the Gabbi-Docs should become a dummies guide to software testing, but I feel Gabbi has the ability to provide an entry level.
I'm fairly new to software testing, but an experienced researcher, and would like people who see this to be able to run with it straight off

**Comment by cdent** [comment]
There's a pull request currently under review called [content-handlers](https://github.com/cdent/gabbi/pull/134) that expands on an existing concept called [response handlers](http://gabbi.readthedocs.io/en/latest/handlers.html). Combined these could make it possible to write a test that looks like this (note that this is not yet true, just an example of something that could be true):

```yaml

tests:
- name: post user and pass to form
   POST: /login
   request_headers:
     content-type: application/x-www-form-urlencoded
   data:
     user: theusername
     password: thepassword
   response_headers:
     set-cookie: /some regex of the cookie/
   response_cookie:
     a_cookie_name: a_cookie_value

- name: use the cookie
   GET: /some_resource
   request_headers:
     cookie: $RESPONSE['some syntax for indicating the cookie']
```

The difficulty then becomes preserving the cookie's value for subsequent tests. If that is necessary, you could probably do this in the content handler or a fixture (as you've already done) and setting the environment.

I think the best thing to do at this point is to carry on with what you're doing, keep writing your results and keep asking questions. From that, if we're lucky, we can extract some kind of "introduction to testing, using gabbi" page to stick in the docs. There's no rush, and no obligation, but if we do happen to reach that it would be a great outcome.

**Comment by martynbristow** [comment]
Brilliant I'll have a look thanks 👍 
And that does sound like a good plan
